spring:
  application:
    name: api-gateway

zuul:
  retryable: true
  sensitive-headers:
  routes:
    carComposition:
      path: /composition/**
      url: forward:/composition/cars/


cars:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true

logging:
  level:
    org.springframework.cloud.netflix: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    fetch-registry: true
    register-with-eureka: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
