server:
  port: 8010

cars:
  counter: 0

spring:
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: cars
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    url: jdbc:mysql://localhost/car?createDatabaseIfNotExist=true
  cloud:
    stream:
      bindings:
        output:
          destination: cars
        hystrixStreamOutput:
          destination: springCloudHystrixStream
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  oauth2:
    client:
      client-id: frontend
      client-secret: secret
      grant-type: password
    resource:
      jwt:
        key-value: supersecretkey

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
