server:
  port: 8010

cars:
  counter: 0

spring:
  application:
    name: cars
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    url: jdbc:mysql://localhost/car?createDatabaseIfNotExist=true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
