server:
  port: 7777

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
spring:
  application:
    admin:
      enabled: true