server:
  port: 8030

spring:
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: trip
  datasource:
    url: jdbc:mysql://localhost/trip?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  cloud:
    stream:
      bindings:
        hystrixStreamOutput:
          destination: springCloudHystrixStream
        input:
          group: trip
          destination: cars
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
security:
  oauth2:
    client:
      client-id: frontend
      client-secret: secret
      grant-type: password
    resource:
      jwt:
        key-value: supersecretkey

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE