server:
  port: 0

spring:
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost/user?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
security:
  oauth2:
    client:
      client-id: frontend
      client-secret: secret
    resource:
      jwt:
        key-value: supersecretkey
